// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARdhOz5d9C-Y39xgHdNcI-yZzypRXkmRI',
    appId: '1:263283798765:web:100d8c76e50f46301692e4',
    messagingSenderId: '263283798765',
    projectId: 'flutter-notes-app-92afb',
    authDomain: 'flutter-notes-app-92afb.firebaseapp.com',
    storageBucket: 'flutter-notes-app-92afb.firebasestorage.app',
    measurementId: 'G-W7KV8GQD9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9YAHB33z8D2WRkocwCZFbiZMVmfhStVI',
    appId: '1:263283798765:android:6c06304ad1c37d6c1692e4',
    messagingSenderId: '263283798765',
    projectId: 'flutter-notes-app-92afb',
    storageBucket: 'flutter-notes-app-92afb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-IsQZgjlfgWOa4EyNg1PPfM3bbwwPqLA',
    appId: '1:263283798765:ios:c4658d04a30b2b301692e4',
    messagingSenderId: '263283798765',
    projectId: 'flutter-notes-app-92afb',
    storageBucket: 'flutter-notes-app-92afb.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-IsQZgjlfgWOa4EyNg1PPfM3bbwwPqLA',
    appId: '1:263283798765:ios:c4658d04a30b2b301692e4',
    messagingSenderId: '263283798765',
    projectId: 'flutter-notes-app-92afb',
    storageBucket: 'flutter-notes-app-92afb.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARdhOz5d9C-Y39xgHdNcI-yZzypRXkmRI',
    appId: '1:263283798765:web:2c4dd5f46bcaeee71692e4',
    messagingSenderId: '263283798765',
    projectId: 'flutter-notes-app-92afb',
    authDomain: 'flutter-notes-app-92afb.firebaseapp.com',
    storageBucket: 'flutter-notes-app-92afb.firebasestorage.app',
    measurementId: 'G-0R65GYVZMT',
  );
}
